version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    ports:
    - "2181:2181"
    networks:
    - kafka-internal-network
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: kafka
    image: quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}  --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
    ]
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    - "9093:9093"
    networks:
    - kafka-internal-network
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_BROKER_ID : 1
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER : "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS : CLIENT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS : CLIENT://kafka:9092,EXTERNAL://localhost:9093
      ALLOW_ANONYMOUS_LOGIN : "yes"
      CONNECTIONS_FROM_HOST : PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1 
      KAFKA_INTER_BROKER_LISTENER_NAME : CLIENT

networks:
    kafka-internal-network:
        name: kafka-network